#$FreeBSD$
# TODO(clutton): remove this comment when more tests would be fixed
# DBUS: env DBUS_FATAL_WARNINGS=0
# ubuntu builds dbus with DBUS_DISABLE_CHECKS and chromium assumes that this
# behaviour is normal (it is not anyway, check the dbus maillist).
# sync_unit_tests
TEST_TARGETS=	base_unittests \
		crypto_unittests \
		cacheinvalidation_unittests \
		gpu_unittests \
		printing_unittests \
		sql_unittests \
		content_unittests \
		cc_unittests \
		url_unittests \
		compositor_unittests \
		ipc_tests \
		dbus_unittests \
		net_unittests \
		media_unittests \
		chromedriver_unittests \
		chromedriver_tests \
		browser_tests \
		unit_tests
